<h4><?php echo $this->__('Module List') ?></h4>
<div style="background: tomato; font-size: 0.75em; color: white;">
    <?php echo get_class($this) . ' => get_class($this)<br />'; ?>
    <?php echo get_class() . ' => get_class()<br />'; ?>
</div>
<hr /><br /><hr />
<div style="background: #d9d9d9;">
    <?php
    $allExamples = $this->getExampleCollection();
    echo "<table style='width:100%'>" .
            "<tr style='background: #E6DF2A;'>" .
                "<th>&nbsp;Example&nbsp;ID&nbsp;</th><th>&nbsp;Name&nbsp;</th><th>&nbsp;Date&nbsp;</th>" .
            "</tr>";
    foreach($allExamples as $example) :
        echo '<tr>';
        echo '<td>&nbsp;' . $example->getExampleId() . '&nbsp;</td>';
        echo '<td>&nbsp;' . $example->getName() . '&nbsp;</td>';
        echo '<td>&nbsp;' . $example->getDate() . '&nbsp;</td>';
        echo '</tr>';
    endforeach;
    echo "</table>";
    ?>
</div>
<br />
<h4><?php echo $this->__('Add an Example') ?></h4>

<form action="<?php echo $this->getFormAction();?>" id="butvin_example_form" method="post">
    <p>
        <label for="ex_name">Name</label> <br />
        <input class="input-text required-entry" id="ex_name" name="ex_name" type="text">
    </p>
    <p>
    <p>
        <button style="margin-top: 0.75em;" class="" type="submit">&nbsp;save&nbsp;</button>
    </p>
</form>

<?php

//$model = Mage::getModel('example/example')->load(1);
//$model->delete();
//$item = $model->getData();

//$io = $model->getOrigData('name');



//$examples = Mage::getModel('example/example')->getCollection()->load(1);
//
//if ($examples) {
//    echo $examples->getExampleId();
//    echo $examples->getTitle();
//    echo $examples->getDate();
//} else {
//    echo "HIXEPA";
//}

/*
This will load one record from your database table.
load(<module>_id) will load whatever ID number you give it.
*/
/*
$news = Mage::getModel('<module>/<module>')->load(1);
echo $news->get<Module>Id();
echo $news->getTitle();
echo $news->getContent();
echo $news->getStatus();
*/

/*
This block of code loads all of the records in the database table.
It will iterate through the collection and the first thing it will do
is set the Title to the current value of $i which is incremented each
iteration and then echo that value back out.  At the very end it will
save the entire collection.
*/
/*
$i = 0;

$collection = Mage::getModel('<module>/<module>')->getCollection();
$collection->setPageSize(5);
$collection->setCurPage(2);
$size = $collection->getSize();
$cnt = count($collection);
foreach ($collection as $item) {
    $i = $i+1;
    $item->setTitle($i);
    echo $item->getTitle();
}

$collection->walk('save');
*/

/*
This shows how to load one value, change something and save it.
*/

/*
$object = Mage::getModel('<module>/<module>')->load(1);
$object->setTitle('This is a changed title');
$object->save();
*/
?>